language: node_js

node_js:
  - node
  - 6
  - 5
  - 4

before_install:
  - phantomjs --version

before_script:
  - npm install -g grunt-cli
  - npm install patternengine-node-underscore
  - npm install patternengine-node-handlebars
  - npm install patternengine-node-twig

branches:
  only:
    - master
    - dev
    - 438-runAllTestsTravis

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a14f537f16b0756d9470
    on_success: always
    on_failure: always
    on_start: never
