language: node_js

before_install:
  - phantomjs --version

before_script:
  - npm install -g lerna@3.0.0-beta.21
  - npm run bootstrap
  - lerna add @pattern-lab/engine-mustache
  - lerna add @pattern-lab/engine-handlebars
  - lerna add @pattern-lab/engine-underscore
  - lerna add @pattern-lab/engine-liquid
  - lerna add @pattern-lab/engine-twig
  - lerna add @pattern-lab/engine-react

branches:
  only:
    - master
    - dev

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a14f537f16b0756d9470
    on_success: always
    on_failure: always
    on_start: never
