language: node_js

addons:
  chrome: stable

before_install:
  # version lifted from `.nvmrc`
  - nvm install
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.0
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn run setup
  - npx lerna add @pattern-lab/engine-handlebars --scope=@pattern-lab/core
  - npx lerna add @pattern-lab/engine-underscore --scope=@pattern-lab/core
  - npx lerna add @pattern-lab/engine-liquid --scope=@pattern-lab/core
  - npx lerna add @pattern-lab/engine-twig --scope=@pattern-lab/core
  - npx lerna add @pattern-lab/engine-react --scope=@pattern-lab/core

script: travis_wait yarn run test

branches:
  only:
    - master
    - dev

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a14f537f16b0756d9470
    on_success: always
    on_failure: always
    on_start: never
